TMP_FOLDER: '/scratch/${USER}/temp/'
KDP_PARAMETERS:
    RMIN : 1000.
    RMAX : 50000.
    RCELL : 1000.
    ZMIN : 20.
    ZMAX : 40.
    RWIND : 6000.
SNR_THRESHOLD: 3
ZH_THRESHOLD: -90
VISIB_CORR:
    MIN_VISIB: 37
    MAX_CORR: 2
SWEEPS: 'all'
RADARS: 'all'
# Post-processing
OUTLIER_REMOVAL: 1
GAUSSIAN_SIGMA: 0.5
ADVECTION_CORRECTION: 0
OUTPUT: 'DN' # either 'DN' (binary), 'float' (binary), or 'DN_gif'
