TMP_FOLDER: '/scratch/${USER}/temp/'
KDP_PARAMETERS:
    RMIN : 1000.
    RMAX : 50000.
    RCELL : 1000.
    ZMIN : 20.
    ZMAX : 40.
    RWIND : 6000.
SNR_THRESHOLD: 3
ZH_THRESHOLD: -90
VISIB_CORR:
    MIN_VISIB: 37
    MAX_CORR: 2
SWEEPS: 'all'
RADARS: 'all'
# Post-processing
OUTLIER_REMOVAL: 1
GAUSSIAN_SIGMA: 0.5
ADVECTION_CORRECTION: 0
DATA_FORMAT: 'float' # either 'float' or 'DN'
FILE_FORMAT: 'ODIM' # either 'ODIM' (hdf5) or 'gif'
CLEANUP: 'delete_all' #if CLEANUP='delete_all', remove all the unzipped files within the temp folder
