NO_DATA_FILL: -9999
TMP_FOLDER: '/scratch/${USER}/temp/'
CONDA_ENV_NAME: 'rainforest_database'
GAUGE_RETRIEVAL:
    VARIABLES : ['tre200s0','prestas0','ure200s0','rre150z0','dkl010z0','fkl010z0','rre150z0_adj']
    STATIONS : 'all'
    MIN_R_HOURLY : 0.01
    MAX_NB_SLURM_JOBS: 6
    
REFERENCE_RETRIEVAL:
    PRODUCTS : ['RZC','CPC','CPCH','CPC.CV','CPC_XLS','AQC_XLS','BZC','MZC','MVRZC','MVCPCH']
    MV_METHOD: 'lucaskanade' # see https://pysteps.readthedocs.io/en/latest/generated/pysteps.motion.interface.get_method.html
    NEIGHBOURS_X : [-1,0,1] # not applied to CPC.CV, CPC_XLS and AQC_XLS
    NEIGHBOURS_Y : [-1,0,1] # not applied to CPC.CV, CPC_XLS and AQC_XLS
    MAX_SIMULTANEOUS_JOBS: 20
    MAX_NB_SLURM_JOBS: 100
    SLURM_JOBS_PER_FILE: 10
    
RADAR_RETRIEVAL:
    RADARS: ['A','D','L','W','P']
    RADAR_VARIABLES : ['ZH','ZV','ZH_VISIB','ZV_VISIB','ZDR','KDP','RHOHV','SW','RVEL','AH','ZH_CORR','ZV_CORR','ZDR_CORR','VISIB','NH','NV'] #,'HYDRO']
    COSMO_VARIABLES: [] #['T','U','V','W','P','QV'] # Only at center pixel
    OTHER_VARIABLES: ['HEIGHT','VPR','RADPRECIP','ISO0_HEIGHT','height_over_iso0'] # Only at center pixel
    TEMP_REF: 'ISO0_HEIGHT' # or 'TAIR'
    AGGREGATION_METHODS: ['max','min','mean'] # value at max/min of kdp for kdp and max/min of zh for all other variables
    SWEEPS: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    NEIGHBOURS_X : [-1,0,1]
    NEIGHBOURS_Y : [-1,0,1]
    KDP_PARAMETERS:
        RMIN : 1000.
        RMAX : 50000.
        RCELL : 1000.
        ZMIN : 20.
        ZMAX : 40.
        RWIND : 6000.
    SNR_THRESHOLD: 3
    VISIB_CORR:
        MIN_VISIB: 37
        MAX_CORR: 2
    MAX_SIMULTANEOUS_JOBS: 20
    MAX_NB_SLURM_JOBS: 100
    SLURM_JOBS_PER_FILE: 10