#!/bin/sh
#SBATCH -N 1     # nodes requested
#SBATCH -c 1      # cores requested
#SBATCH --mem-per-cpu 64g # memory in mbytes  
#SBATCH -t 23:59:59  # time requested in hour:minute:second
qpe_compute -s 201908060000 -e 201908070000 -m '{"RF_dualpol":"dualpol_model_BC_spline.p"}' -o /scratch/wolfensb/qpe_runs/20190806