package:
  name: rainforest
  version: 1.0

source:
  git_rev: 1.0
  git_url: https://github.com/MeteoSwiss/rainforest

requirements:
  build:
    - git
  run:
    - pyspark
    - netCDF4
    - prompt_toolkit
    - scikit-learn
    - numpy
    - dask
    - pandas
    - xmltodict
    - pyart_mch
    - scipy
 
test:
  imports:
    -

about:
  home:
