package:
  name: rainforest
  version: 1.1

source:
  # Relative path to the parent directory.
  path: ..
     
requirements:
  build:
    - git
  run:
    - pyspark
    - netCDF4
    - prompt_toolkit
    - scikit-learn
    - numpy
    - pyart_mch
    - dask
    - pandas
    - xmltodict
    - scipy
    - pyshp
    - imageio
 
about:
  home:
