TMP_FOLDER: '/tmp/'
KDP_PARAMETERS:
    RMIN : 1000.
    RMAX : 50000.
    RCELL : 1000.
    ZMIN : 20.
    ZMAX : 40.
    RWIND : 6000.
SNR_THRESHOLD: 3
ZH_THRESHOLD: -90
VISIB_CORR:
    MIN_VISIB: 37
    MAX_CORR: 2
SWEEPS: [1,2,3,4,5,6]
RADARS: ['A','D','L','P','W']
# Post-processing
OUTLIER_REMOVAL: 1
GAUSSIAN_SIGMA: 0.5
ADVECTION_CORRECTION: 0
SAVE_NON_POSTPROCESSED_DATA : 0 # 0 for no, 1 for yes
SAVE_FEATURES: 0
DATA_FORMAT: 'float' # either 'float' or 'DN'
FILE_FORMAT: 'ODIM' # either 'ODIM' (hdf5) or 'gif'
