#!/bin/sh
#SBATCH -N 1     # nodes requested
#SBATCH -c 1      # cores requested
#SBATCH --mem-per-cpu 64g # memory in mbytes  
#SBATCH -t 23:59:59  # time requested in hour:minute:second
qpe_compute -s 201911240000 -e 201911250000 -m '{"RF_dualpol":"dualpol_model_BC_spline.p","RF_hpol":"hpol_model_BC_spline.p","RF_vpol":"vpol_model_BC_spline.p"}' -o /scratch/wolfensb/qpe_runs/20191124