#!/bin/sh
#SBATCH -N 1     # nodes requested
#SBATCH -c 1      # cores requested
#SBATCH --mem-per-cpu 64g # memory in mbytes  
#SBATCH -t 23:59:59  # time requested in hour:minute:second
qpe_plot -i /scratch/wolfensb/qpe_runs/20190806 -o /scratch/wolfensb/qpe_runs/plots -V 80 -t 3 -m "RZC, CPC, RF_dualpol","RF_dualpol_ac"