name: rainforest-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - Cython
  - numpy
  - netCDF4
  - prompt_toolkit
  - scikit-learn==1.2.2
  - scipy
  - dask
  - pandas
  - pyspark
  - pyart_mch
  - xmltodict
  - pyshp
  - imageio
  - boto3
  - pyarrow
  - h5py
  - pysteps
  - xlrd
  - pyproj
