name: build-deploy-site

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
   contents: write
   
# This job installs dependencies, build the website, and pushes it to `gh-pages`
jobs:
  deploy-website:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install rainforest
        if: matrix.os != 'macos-latest'
        working-directory: ${{github.workspace}}
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r ./docs/requirements.txt
          pip install .
      # Build the website
      - name: Build the site
        run: |
          cd docs
          make html
        env:
          AWS_KEY: ${{ secrets.AWS_KEY }}
          RAINFOREST_DATAPATH:  ${{github.workspace}}/rainforest_data
      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          cname: https:/meteoswiss.github.io/rainforest/
